### ISSUE TITLE
Bzr export fails with type conversion fatal

### ISSUE THREAD

**Issue by neclimdul** [jelmer/python-fastimport#13]
Trace:
```
brz: ERROR: TypeError: can't concat str to bytes

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/breezy/commands.py", line 1016, in exception_to_return_code
    return the_callable(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/breezy/commands.py", line 1202, in run_bzr
    ret = run(*run_argv)
  File "/usr/lib/python3/dist-packages/breezy/commands.py", line 759, in run_argv_aliases
    return self.run(**all_cmd_args)
  File "/usr/lib/python3/dist-packages/breezy/commands.py", line 784, in run
    return self._operation.run_simple(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/breezy/cleanup.py", line 137, in run_simple
    self.cleanups, self.func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/breezy/cleanup.py", line 166, in _do_with_cleanups
    result = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/breezy/plugins/fastimport/cmds.py", line 507, in run
    return exporter.run()
  File "/usr/lib/python3/dist-packages/breezy/plugins/fastimport/exporter.py", line 253, in run
    self.emit_commit(revid, self.ref)
  File "/usr/lib/python3/dist-packages/breezy/plugins/fastimport/exporter.py", line 372, in emit_commit
    self.print_cmd(self._get_commit_command(ref, mark, revobj, file_cmds))
  File "/usr/lib/python3/dist-packages/breezy/plugins/fastimport/exporter.py", line 299, in print_cmd
    self.outf.write(b"%s\n" % cmd)
  File "/usr/lib/python3/dist-packages/fastimport/commands.py", line 189, in __bytes__
    return self.to_string(include_file_contents=True)
  File "/usr/lib/python3/dist-packages/fastimport/commands.py", line 242, in to_string
    for c in self.iter_files()])
  File "/usr/lib/python3/dist-packages/fastimport/commands.py", line 242, in <listcomp>
    for c in self.iter_files()])
  File "/usr/lib/python3/dist-packages/fastimport/helpers.py", line 120, in repr_bytes
    return bytes(obj)
  File "/usr/lib/python3/dist-packages/fastimport/commands.py", line 367, in __bytes__
    return self.to_string(include_file_contents=True)
  File "/usr/lib/python3/dist-packages/fastimport/commands.py", line 393, in to_string
    datastr = ('\ndata %d\n' % len(self.data)).encode('ascii') + self.data
TypeError: can't concat str to bytes
```
The problem seems to be that in FileModifyCommand data ends up with a string instead of the bytes its suppose to have.

I've gone up and down this a couple times and can't immediately see what this would happen. Things seem pretty strict about using bytes.

My I'm sure absolutely wrong hack I'm playing with is just this but maybe you have a better grasp on what's happening.
```
                if (type(self.data) == str):
                  datastr = ('\ndata %d\n' % len(self.data)).encode('ascii') + self.data.encode('ascii')
                else:
                  datastr = ('\ndata %d\n' % len(self.data)).encode('ascii') + self.data
```

**Comment by jelmer** [comment]
This is a bug in bzr-fastimport, it should be passing in bytes.

**Comment by neclimdul** [comment]
If someone stumbles through this, it was fixed in breezy just not the version in the current version of ubuntu as of this writing.

https://bugs.launchpad.net/brz/+bug/1805172
